name: root
channels:
  - defaults
  - pyviz/label/dev
  - bokeh/label/dev
  - intake
  - conda-forge
dependencies:
  - intake-astro
  - intake-parquet
  - cartopy
  - intake-xarray
  - astropy
  - sunpy
  - jupyterhub
  - bokeh
  - bqplot
  - cython
  - cytoolz
  - dask=0.19
  - dask-ml
  - datashader
  - distributed
  - fastparquet
  - gcsfs
  - ipywidgets
  - ipyleaflet
  - jupyter
  - jupyterlab
  - jupyterlab_launcher
  - jupyter_client
  - holoviews
  - libsodium
  - lz4
  - matplotlib
  - nb_conda_kernels
  - nomkl
  - numba
  - numcodecs
  - numpy
  - pandas
  - python-blosc
  - pyzmq
  - s3fs
  - scipy
  - scikit-image
  - scikit-learn
  - xarray
  - zarr
  - intake-xarray
  - graphviz
  - python-graphviz
  - gsw
  - nodejs
  - dask-kubernetes
  - nbserverproxy
  - pip:
    - click
    - jedi
    - git+https://github.com/sunpy/sunpy.git
